export default {
  "code": "SUCCESS",
  "msg": null,
  "requestId": null,
  "data": {
    "businessAdminId": 500427,
    "loginName": "spadmin",
    "password": "",
    "realName": "spadmin",
    "idCard": "18771078756",
    "mobile": "11011112222",
    "adminType": 0,
    "status": 1,
    "disabled": false,
    "lastLoginTime": 1560850404000,
    "businessRoleIdList": null,
    "createTime": 1560850404000,
    "modifyTime": 1563521024000,
    "urlSet": [
      "/manager/index/agentsDataList",
      "/manager/risk/history/queryPage",
      "/manager/agents/report/queryList",
      "/manager/user/agents/editAppKeySecret",
      "/manager/updownHistory/queryPage",
      "/manager/user/agents/addAgents",
      "/manager/gold/stock/getByGameGoldId",
      "/manager/user/agents/editAgentsStatus",
      "/manager/gold/queryList",
      "/manager/system/role/updateByBusinessRoleId",
      "/manager/notice/disable",
      "/manager/push/getByBusinessPushId",
      "/manager/system/role/getMenuTree",
      "/manager/push/insertOrUpdate",
      "/manager/roundHistory/queryUserComplexPage",
      "/manager/activity/report/getSum",
      "/manager/charge/getCreditChargeTotal",
      "/manager/activity/getByUserAgentsId",
      "/manager/push/queryPage",
      "/manager/updownHistory/export",
      "/manager/system/role/getByBusinessRoleId",
      "/manager/gold/delete",
      "/manager/notice/queryPage",
      "/manager/gold/queryPage",
      "/manager/user/agents/editWhiteIp",
      "/manager/system/role/deleteByBusinessRoleId",
      "/manager/activity/insert",
      "/manager/system/role/page",
      "/manager/agents/report/getSum",
      "/manager/activity/page",
      "/manager/risk/config/delete",
      "/manager/system/log/page",
      "/manager/index/agentsTopData",
      "/manager/user/agents/page",
      "/manager/risk/config/getByBusinessRiskConfigId",
      "/manager/system/admin/deleteByBusinessAdminId",
      "/manager/activity/deleteByActivityId",
      "/manager/user/agents/getByUserAgentsId",
      "/manager/push/delete",
      "/manager/gold/insertOrUpdate",
      "/game/config/insertOrUpdate",
      "/manager/user/agents/agentsCharge",
      "/manager/system/admin/editAdmin",
      "msg/pushList.html",
      "/manager/user/agents/editAgents",
      "/manager/notice/delete",
      "/manager/retention/queryList",
      "charge/chargeList.html",
      "/manager/risk/config/changeStatus",
      "gold/goldStockList.html",
      "/manager/system/admin/getByBusinessAdminId",
      "/manager/charge/page",
      "/manager/system/role/insert",
      "/manager/report/goldtype/queryReport",
      "/game/config/getByGameConfigId",
      "/manager/risk/config/queryPage",
      "/manager/notice/getByBusinessNoticeId",
      "/manager/activity/record/page",
      "/manager/gold/stock/updateCurrentStock",
      "/manager/activity/updateByActivityId",
      "/game/config/delete",
      "/manager/gold/stock/queryPage",
      "gameconfig/configList.html",
      "/manager/notice/insertOrUpdate",
      "/manager/risk/config/insertOrUpdate",
      "msg/noticeList.html",
      "/manager/system/admin/addAdmin",
      "/manager/activity/report/queryList",
      "/manager/system/admin/page",
      "/manager/user/agents/createAppKeySecret",
      "/manager/gold/stock/disable",
      "/manager/gold/getByGameGoldId",
      "/manager/push/disable",
      "/game/config/queryPage",
      "/manager/gold/disable",
      "gold/goldList.html",
      "/manager/user/agents/editMaxCredit",
      "/manager/charge/repaymentCredit",
      "/manager/gold/stock/insertOrUpdate"
    ],
    "menuCodeSet": [
      "m_013_001",
      "m_005_005",
      "m_013_002",
      "m_005_004",
      "m_005_006",
      "m_005_001",
      "m_005_005_001",
      "m_005_003",
      "m_005_002",
      "m_005_005_004",
      "m_005_005_002",
      "m_005_005_003",
      "m_003_001",
      "m_012_001",
      "m_005_006_001",
      "m_005_006_002",
      "m_011_001_002",
      "m_011_001_001",
      "m_011_001_003",
      "m_011_002",
      "m_011_001",
      "m_011_002_003",
      "m_014",
      "m_011_002_002",
      "m_013",
      "m_011_002_001",
      "m_013_001_003",
      "m_013_001_001",
      "m_013_001_002",
      "m_013_002_001",
      "m_013_002_002",
      "m_013_002_003",
      "m_003_001_001",
      "m_005",
      "m_004",
      "m_009_004",
      "m_003",
      "m_002",
      "m_009",
      "m_009_001",
      "m_008",
      "m_009_003",
      "m_005_001_001",
      "m_009_002",
      "m_006",
      "m_012",
      "m_011",
      "m_002_002",
      "m_002_001",
      "m_012_001_001",
      "m_002_003",
      "m_014_002",
      "m_001",
      "m_002_001_005",
      "m_001_001",
      "m_002_001_006",
      "m_002_001_007",
      "m_014_001",
      "m_002_001_001",
      "m_005_004_002",
      "m_002_001_002",
      "m_005_004_001",
      "m_002_001_003",
      "m_002_001_004",
      "m_005_004_003"
    ],
    "menuList": [
      {
        "businessMenuId": 1286,
        "menuCode": "m_001",
        "menuName": "首页",
        "parentMenuCode": "0",
        "sysType": 1,
        "menuType": 1,
        "sort": 0,
        "disabled": false,
        "createTime": 1560914957000,
        "modifyTime": 1560937778000,
        "url": null,
        "childList": [
          {
            "businessMenuId": 1333,
            "menuCode": "m_001_001",
            "menuName": "首页数据",
            "parentMenuCode": "m_001",
            "sysType": 1,
            "menuType": 1,
            "sort": 0,
            "disabled": false,
            "createTime": 1560936641000,
            "modifyTime": 1562571662000,
            "url": "/manager/index/agentsTopData,/manager/index/agentsDataList",
            "childList": [],
            "isCheck": true
          }
        ],
        "isCheck": true
      },
      {
        "businessMenuId": 1287,
        "menuCode": "m_003",
        "menuName": "运营",
        "parentMenuCode": "0",
        "sysType": 1,
        "menuType": 1,
        "sort": 0,
        "disabled": false,
        "createTime": 1560937801000,
        "modifyTime": 1560937940000,
        "url": null,
        "childList": [
          {
            "businessMenuId": 1291,
            "menuCode": "m_011",
            "menuName": "金币场管理",
            "parentMenuCode": "m_003",
            "sysType": 1,
            "menuType": 1,
            "sort": 0,
            "disabled": false,
            "createTime": 1560936608000,
            "modifyTime": 1560938964000,
            "url": null,
            "childList": [
              {
                "businessMenuId": 1292,
                "menuCode": "m_011_001",
                "menuName": "金币场列表",
                "parentMenuCode": "m_011",
                "sysType": 1,
                "menuType": 1,
                "sort": 0,
                "disabled": false,
                "createTime": 1560936641000,
                "modifyTime": 1562049111000,
                "url": "gold/goldList.html,/manager/gold/queryPage",
                "childList": [
                  {
                    "businessMenuId": 1293,
                    "menuCode": "m_011_001_001",
                    "menuName": "金币场添加/修改",
                    "parentMenuCode": "m_011_001",
                    "sysType": 1,
                    "menuType": 2,
                    "sort": 0,
                    "disabled": false,
                    "createTime": 1560936641000,
                    "modifyTime": 1562049116000,
                    "url": "/manager/gold/getByGameGoldId,/manager/gold/insertOrUpdate",
                    "childList": [],
                    "isCheck": true
                  },
                  {
                    "businessMenuId": 1294,
                    "menuCode": "m_011_001_002",
                    "menuName": "金币场启/禁用",
                    "parentMenuCode": "m_011_001",
                    "sysType": 1,
                    "menuType": 2,
                    "sort": 0,
                    "disabled": false,
                    "createTime": 1560936641000,
                    "modifyTime": 1562049117000,
                    "url": "/manager/gold/disable",
                    "childList": [],
                    "isCheck": true
                  },
                  {
                    "businessMenuId": 1295,
                    "menuCode": "m_011_001_003",
                    "menuName": "金币场删除",
                    "parentMenuCode": "m_011_001",
                    "sysType": 1,
                    "menuType": 2,
                    "sort": 0,
                    "disabled": false,
                    "createTime": 1560936641000,
                    "modifyTime": 1562049121000,
                    "url": "/manager/gold/delete",
                    "childList": [],
                    "isCheck": true
                  }
                ],
                "isCheck": true
              },
              {
                "businessMenuId": 1307,
                "menuCode": "m_011_002",
                "menuName": "库存配置",
                "parentMenuCode": "m_011",
                "sysType": 1,
                "menuType": 1,
                "sort": 0,
                "disabled": false,
                "createTime": 1562049018000,
                "modifyTime": 1562049138000,
                "url": "gold/goldStockList.html,/manager/gold/stock/queryPage,/manager/gold/queryList",
                "childList": [
                  {
                    "businessMenuId": 1308,
                    "menuCode": "m_011_002_001",
                    "menuName": "库存添加/修改",
                    "parentMenuCode": "m_011_002",
                    "sysType": 1,
                    "menuType": 2,
                    "sort": 0,
                    "disabled": false,
                    "createTime": 1562049201000,
                    "modifyTime": 1562049277000,
                    "url": "/manager/gold/stock/insertOrUpdate,/manager/gold/stock/getByGameGoldId",
                    "childList": [],
                    "isCheck": true
                  },
                  {
                    "businessMenuId": 1309,
                    "menuCode": "m_011_002_002",
                    "menuName": "库存启用/禁用",
                    "parentMenuCode": "m_011_002",
                    "sysType": 1,
                    "menuType": 2,
                    "sort": 0,
                    "disabled": false,
                    "createTime": 1562049229000,
                    "modifyTime": 1562049280000,
                    "url": "/manager/gold/stock/disable",
                    "childList": [],
                    "isCheck": true
                  },
                  {
                    "businessMenuId": 1310,
                    "menuCode": "m_011_002_003",
                    "menuName": "当前库存修改",
                    "parentMenuCode": "m_011_002",
                    "sysType": 1,
                    "menuType": 2,
                    "sort": 0,
                    "disabled": false,
                    "createTime": 1562049258000,
                    "modifyTime": 1562049282000,
                    "url": "/manager/gold/stock/updateCurrentStock",
                    "childList": [],
                    "isCheck": true
                  }
                ],
                "isCheck": true
              }
            ],
            "isCheck": true
          },
          {
            "businessMenuId": 1324,
            "menuCode": "m_013",
            "menuName": "消息管理",
            "parentMenuCode": "m_003",
            "sysType": 1,
            "menuType": 1,
            "sort": 0,
            "disabled": false,
            "createTime": 1560936608000,
            "modifyTime": 1560938964000,
            "url": "",
            "childList": [
              {
                "businessMenuId": 1325,
                "menuCode": "m_013_001",
                "menuName": "公告通知",
                "parentMenuCode": "m_013",
                "sysType": 1,
                "menuType": 1,
                "sort": 0,
                "disabled": false,
                "createTime": 1560936641000,
                "modifyTime": 1562729582000,
                "url": "msg/noticeList.html,/manager/notice/queryPage",
                "childList": [
                  {
                    "businessMenuId": 1327,
                    "menuCode": "m_013_001_001",
                    "menuName": "公告添加/修改",
                    "parentMenuCode": "m_013_001",
                    "sysType": 1,
                    "menuType": 2,
                    "sort": 0,
                    "disabled": false,
                    "createTime": 1560936641000,
                    "modifyTime": 1562729679000,
                    "url": "/manager/notice/getByBusinessNoticeId,/manager/notice/insertOrUpdate",
                    "childList": [],
                    "isCheck": true
                  },
                  {
                    "businessMenuId": 1328,
                    "menuCode": "m_013_001_002",
                    "menuName": "公告启/禁用",
                    "parentMenuCode": "m_013_001",
                    "sysType": 1,
                    "menuType": 2,
                    "sort": 0,
                    "disabled": false,
                    "createTime": 1560936641000,
                    "modifyTime": 1562729676000,
                    "url": "/manager/notice/disable",
                    "childList": [],
                    "isCheck": true
                  },
                  {
                    "businessMenuId": 1329,
                    "menuCode": "m_013_001_003",
                    "menuName": "公告删除",
                    "parentMenuCode": "m_013_001",
                    "sysType": 1,
                    "menuType": 2,
                    "sort": 0,
                    "disabled": false,
                    "createTime": 1560936641000,
                    "modifyTime": 1562729674000,
                    "url": "/manager/notice/delete",
                    "childList": [],
                    "isCheck": true
                  }
                ],
                "isCheck": true
              },
              {
                "businessMenuId": 1326,
                "menuCode": "m_013_002",
                "menuName": "推送消息",
                "parentMenuCode": "m_013",
                "sysType": 1,
                "menuType": 1,
                "sort": 0,
                "disabled": false,
                "createTime": 1560936641000,
                "modifyTime": 1562751099000,
                "url": "msg/pushList.html,/manager/push/queryPage",
                "childList": [
                  {
                    "businessMenuId": 1330,
                    "menuCode": "m_013_002_001",
                    "menuName": "推送添加/修改",
                    "parentMenuCode": "m_013_002",
                    "sysType": 1,
                    "menuType": 2,
                    "sort": 0,
                    "disabled": false,
                    "createTime": 1560936641000,
                    "modifyTime": 1562751112000,
                    "url": "/manager/push/getByBusinessPushId,/manager/push/insertOrUpdate",
                    "childList": [],
                    "isCheck": true
                  },
                  {
                    "businessMenuId": 1331,
                    "menuCode": "m_013_002_002",
                    "menuName": "推送启/禁用",
                    "parentMenuCode": "m_013_002",
                    "sysType": 1,
                    "menuType": 2,
                    "sort": 0,
                    "disabled": false,
                    "createTime": 1560936641000,
                    "modifyTime": 1562751117000,
                    "url": "/manager/push/disable",
                    "childList": [],
                    "isCheck": true
                  },
                  {
                    "businessMenuId": 1332,
                    "menuCode": "m_013_002_003",
                    "menuName": "推送删除",
                    "parentMenuCode": "m_013_002",
                    "sysType": 1,
                    "menuType": 2,
                    "sort": 0,
                    "disabled": false,
                    "createTime": 1560936641000,
                    "modifyTime": 1562751115000,
                    "url": "/manager/push/delete",
                    "childList": [],
                    "isCheck": true
                  }
                ],
                "isCheck": true
              }
            ],
            "isCheck": true
          },
          {
            "businessMenuId": 1351,
            "menuCode": "m_003_001",
            "menuName": "活动管理",
            "parentMenuCode": "m_003",
            "sysType": 1,
            "menuType": 1,
            "sort": 0,
            "disabled": false,
            "createTime": 1561433653000,
            "modifyTime": 1563867885000,
            "url": "",
            "childList": [
              {
                "businessMenuId": 1352,
                "menuCode": "m_003_001_001",
                "menuName": "活动列表",
                "parentMenuCode": "m_003_001",
                "sysType": 1,
                "menuType": 1,
                "sort": 0,
                "disabled": false,
                "createTime": 1561433653000,
                "modifyTime": 1563867885000,
                "url": "/manager/activity/page,/manager/activity/getByUserAgentsId,/manager/activity/insert,/manager/activity/updateByActivityId,/manager/activity/deleteByActivityId",
                "childList": [],
                "isCheck": true
              }
            ],
            "isCheck": true
          }
        ],
        "isCheck": true
      },
      {
        "businessMenuId": 1288,
        "menuCode": "m_009",
        "menuName": "系统",
        "parentMenuCode": "0",
        "sysType": 1,
        "menuType": 1,
        "sort": 0,
        "disabled": false,
        "createTime": 1560914994000,
        "modifyTime": 1560928346000,
        "url": null,
        "childList": [
          {
            "businessMenuId": 1289,
            "menuCode": "m_009_001",
            "menuName": "系统用户管理",
            "parentMenuCode": "m_009",
            "sysType": 1,
            "menuType": 1,
            "sort": 0,
            "disabled": false,
            "createTime": 1560915037000,
            "modifyTime": 1561433585000,
            "url": "/manager/system/admin/page,/manager/system/admin/addAdmin,/manager/system/admin/editAdmin,/manager/system/admin/deleteByBusinessAdminId,/manager/system/admin/getByBusinessAdminId",
            "childList": [],
            "isCheck": true
          },
          {
            "businessMenuId": 1290,
            "menuCode": "m_009_002",
            "menuName": "角色管理",
            "parentMenuCode": "m_009",
            "sysType": 1,
            "menuType": 1,
            "sort": 0,
            "disabled": false,
            "createTime": 1560915060000,
            "modifyTime": 1561433589000,
            "url": "/manager/system/role/page,/manager/system/role/insert,/manager/system/role/updateByBusinessRoleId,/manager/system/role/deleteByBusinessRoleId,/manager/system/role/getByBusinessRoleId,/manager/system/role/getMenuTree",
            "childList": [],
            "isCheck": true
          },
          {
            "businessMenuId": 1302,
            "menuCode": "m_009_003",
            "menuName": "系统配置",
            "parentMenuCode": "m_009",
            "sysType": 1,
            "menuType": 1,
            "sort": 0,
            "disabled": false,
            "createTime": 1561429145000,
            "modifyTime": 1561433593000,
            "url": "gameconfig/configList.html,/game/config/delete,/game/config/getByGameConfigId,/game/config/insertOrUpdate,/game/config/queryPage",
            "childList": [],
            "isCheck": true
          },
          {
            "businessMenuId": 1334,
            "menuCode": "m_009_004",
            "menuName": "操作日志",
            "parentMenuCode": "m_009",
            "sysType": 1,
            "menuType": 1,
            "sort": 0,
            "disabled": false,
            "createTime": 1562913689000,
            "modifyTime": 1562913734000,
            "url": "/manager/system/log/page",
            "childList": [],
            "isCheck": true
          }
        ],
        "isCheck": true
      },
      {
        "businessMenuId": 1296,
        "menuCode": "m_002",
        "menuName": "用户",
        "parentMenuCode": "0",
        "sysType": 1,
        "menuType": 1,
        "sort": 0,
        "disabled": false,
        "createTime": 1560937801000,
        "modifyTime": 1560937940000,
        "url": null,
        "childList": [
          {
            "businessMenuId": 1303,
            "menuCode": "m_002_001",
            "menuName": "代理管理",
            "parentMenuCode": "m_002",
            "sysType": 1,
            "menuType": 1,
            "sort": 0,
            "disabled": false,
            "createTime": 1561433653000,
            "modifyTime": 1562037757000,
            "url": "/manager/user/agents/page,/manager/user/agents/getByUserAgentsId",
            "childList": [
              {
                "businessMenuId": 1306,
                "menuCode": "m_002_001_001",
                "menuName": "代理新增",
                "parentMenuCode": "m_002_001",
                "sysType": 1,
                "menuType": 1,
                "sort": 0,
                "disabled": false,
                "createTime": 1561433653000,
                "modifyTime": 1562039259000,
                "url": "/manager/user/agents/addAgents,/manager/user/agents/createAppKeySecret",
                "childList": [],
                "isCheck": true
              },
              {
                "businessMenuId": 1311,
                "menuCode": "m_002_001_002",
                "menuName": "代理编辑",
                "parentMenuCode": "m_002_001",
                "sysType": 1,
                "menuType": 1,
                "sort": 0,
                "disabled": false,
                "createTime": 1561433653000,
                "modifyTime": 1562039259000,
                "url": "/manager/user/agents/editAgents",
                "childList": [],
                "isCheck": true
              },
              {
                "businessMenuId": 1312,
                "menuCode": "m_002_001_003",
                "menuName": "代理封停",
                "parentMenuCode": "m_002_001",
                "sysType": 1,
                "menuType": 1,
                "sort": 0,
                "disabled": false,
                "createTime": 1561433653000,
                "modifyTime": 1562039259000,
                "url": "/manager/user/agents/editAgentsStatus",
                "childList": [],
                "isCheck": true
              },
              {
                "businessMenuId": 1313,
                "menuCode": "m_002_001_004",
                "menuName": "额度调整",
                "parentMenuCode": "m_002_001",
                "sysType": 1,
                "menuType": 1,
                "sort": 0,
                "disabled": false,
                "createTime": 1561433653000,
                "modifyTime": 1562039259000,
                "url": "/manager/user/agents/editMaxCredit",
                "childList": [],
                "isCheck": true
              },
              {
                "businessMenuId": 1314,
                "menuCode": "m_002_001_005",
                "menuName": "密钥调整",
                "parentMenuCode": "m_002_001",
                "sysType": 1,
                "menuType": 1,
                "sort": 0,
                "disabled": false,
                "createTime": 1561433653000,
                "modifyTime": 1562039259000,
                "url": "/manager/user/agents/editAppKeySecret",
                "childList": [],
                "isCheck": true
              },
              {
                "businessMenuId": 1315,
                "menuCode": "m_002_001_006",
                "menuName": "白名单编辑",
                "parentMenuCode": "m_002_001",
                "sysType": 1,
                "menuType": 1,
                "sort": 0,
                "disabled": false,
                "createTime": 1561433653000,
                "modifyTime": 1562039259000,
                "url": "/manager/user/agents/editWhiteIp",
                "childList": [],
                "isCheck": true
              },
              {
                "businessMenuId": 1316,
                "menuCode": "m_002_001_007",
                "menuName": "代理充值",
                "parentMenuCode": "m_002_001",
                "sysType": 1,
                "menuType": 1,
                "sort": 0,
                "disabled": false,
                "createTime": 1561433653000,
                "modifyTime": 1562121494000,
                "url": "/manager/user/agents/agentsCharge",
                "childList": [],
                "isCheck": true
              }
            ],
            "isCheck": true
          },
          {
            "businessMenuId": 1304,
            "menuCode": "m_002_002",
            "menuName": "玩家管理",
            "parentMenuCode": "m_002",
            "sysType": 1,
            "menuType": 1,
            "sort": 0,
            "disabled": false,
            "createTime": 1561433673000,
            "modifyTime": null,
            "url": null,
            "childList": [],
            "isCheck": true
          },
          {
            "businessMenuId": 1305,
            "menuCode": "m_002_003",
            "menuName": "角色管理",
            "parentMenuCode": "m_002",
            "sysType": 1,
            "menuType": 1,
            "sort": 0,
            "disabled": false,
            "createTime": 1561433697000,
            "modifyTime": null,
            "url": null,
            "childList": [],
            "isCheck": true
          }
        ],
        "isCheck": true
      },
      {
        "businessMenuId": 1297,
        "menuCode": "m_004",
        "menuName": "账户",
        "parentMenuCode": "0",
        "sysType": 1,
        "menuType": 1,
        "sort": 0,
        "disabled": false,
        "createTime": 1560937801000,
        "modifyTime": 1560937940000,
        "url": null,
        "childList": [
          {
            "businessMenuId": 1320,
            "menuCode": "m_012",
            "menuName": "订单管理",
            "parentMenuCode": "m_004",
            "sysType": 1,
            "menuType": 1,
            "sort": 0,
            "disabled": false,
            "createTime": 1560936608000,
            "modifyTime": 1562572001000,
            "url": "",
            "childList": [
              {
                "businessMenuId": 1321,
                "menuCode": "m_012_001",
                "menuName": "充值管理",
                "parentMenuCode": "m_012",
                "sysType": 1,
                "menuType": 1,
                "sort": 0,
                "disabled": false,
                "createTime": 1560936641000,
                "modifyTime": 1562571662000,
                "url": "charge/chargeList.html,/manager/charge/getCreditChargeTotal,/manager/charge/page",
                "childList": [
                  {
                    "businessMenuId": 1322,
                    "menuCode": "m_012_001_001",
                    "menuName": "信用还款",
                    "parentMenuCode": "m_012_001",
                    "sysType": 1,
                    "menuType": 2,
                    "sort": 0,
                    "disabled": false,
                    "createTime": 1562049201000,
                    "modifyTime": 1562571710000,
                    "url": "/manager/charge/repaymentCredit",
                    "childList": [],
                    "isCheck": true
                  }
                ],
                "isCheck": true
              }
            ],
            "isCheck": true
          }
        ],
        "isCheck": true
      },
      {
        "businessMenuId": 1298,
        "menuCode": "m_005",
        "menuName": "数据",
        "parentMenuCode": "0",
        "sysType": 1,
        "menuType": 1,
        "sort": 0,
        "disabled": false,
        "createTime": 1560937801000,
        "modifyTime": 1560937940000,
        "url": null,
        "childList": [
          {
            "businessMenuId": 1319,
            "menuCode": "m_005_001",
            "menuName": "代理数据",
            "parentMenuCode": "m_005",
            "sysType": 1,
            "menuType": 1,
            "sort": 0,
            "disabled": false,
            "createTime": 1561433653000,
            "modifyTime": 1563867885000,
            "url": "",
            "childList": [
              {
                "businessMenuId": 1343,
                "menuCode": "m_005_001_001",
                "menuName": "上下分明细",
                "parentMenuCode": "m_005_001",
                "sysType": 1,
                "menuType": 1,
                "sort": 0,
                "disabled": false,
                "createTime": 1561433653000,
                "modifyTime": 1562121494000,
                "url": "/manager/updownHistory/queryPage,/manager/updownHistory/export",
                "childList": [],
                "isCheck": true
              }
            ],
            "isCheck": true
          },
          {
            "businessMenuId": 1323,
            "menuCode": "m_005_002",
            "menuName": "历史战绩",
            "parentMenuCode": "m_005",
            "sysType": 1,
            "menuType": 1,
            "sort": 0,
            "disabled": false,
            "createTime": 1561433653000,
            "modifyTime": 1562121494000,
            "url": "/manager/roundHistory/queryUserComplexPage",
            "childList": [],
            "isCheck": true
          },
          {
            "businessMenuId": 1338,
            "menuCode": "m_005_003",
            "menuName": "场次数据",
            "parentMenuCode": "m_005",
            "sysType": 1,
            "menuType": 1,
            "sort": 0,
            "disabled": false,
            "createTime": 1561433653000,
            "modifyTime": 1563269848000,
            "url": "/manager/report/goldtype/queryReport",
            "childList": [],
            "isCheck": true
          },
          {
            "businessMenuId": 1342,
            "menuCode": "m_005_004",
            "menuName": "玩家数据",
            "parentMenuCode": "m_005",
            "sysType": 1,
            "menuType": 1,
            "sort": 0,
            "disabled": false,
            "createTime": 1561433653000,
            "modifyTime": 1563269848000,
            "url": "",
            "childList": [
              {
                "businessMenuId": 1339,
                "menuCode": "m_005_004_001",
                "menuName": "玩家趋势",
                "parentMenuCode": "m_005_004",
                "sysType": 1,
                "menuType": 1,
                "sort": 0,
                "disabled": false,
                "createTime": 1561433653000,
                "modifyTime": 1563867052000,
                "url": "/manager/agents/report/getSum,/manager/agents/report/queryList",
                "childList": [],
                "isCheck": true
              },
              {
                "businessMenuId": 1340,
                "menuCode": "m_005_004_002",
                "menuName": "玩家活跃",
                "parentMenuCode": "m_005_004",
                "sysType": 1,
                "menuType": 1,
                "sort": 0,
                "disabled": false,
                "createTime": 1561433653000,
                "modifyTime": 1563867052000,
                "url": "/manager/agents/report/getSum,/manager/agents/report/queryList",
                "childList": [],
                "isCheck": true
              },
              {
                "businessMenuId": 1341,
                "menuCode": "m_005_004_003",
                "menuName": "玩家留存",
                "parentMenuCode": "m_005_004",
                "sysType": 1,
                "menuType": 1,
                "sort": 0,
                "disabled": false,
                "createTime": 1561433653000,
                "modifyTime": 1563867069000,
                "url": "/manager/retention/queryList",
                "childList": [],
                "isCheck": true
              }
            ],
            "isCheck": true
          },
          {
            "businessMenuId": 1344,
            "menuCode": "m_005_005",
            "menuName": "金币场数据",
            "parentMenuCode": "m_005",
            "sysType": 1,
            "menuType": 1,
            "sort": 0,
            "disabled": false,
            "createTime": 1561433653000,
            "modifyTime": 1563269848000,
            "url": "",
            "childList": [
              {
                "businessMenuId": 1345,
                "menuCode": "m_005_005_001",
                "menuName": "金币场运营",
                "parentMenuCode": "m_005_005",
                "sysType": 1,
                "menuType": 1,
                "sort": 0,
                "disabled": false,
                "createTime": 1561433653000,
                "modifyTime": 1563269848000,
                "url": "/manager/report/goldtype/queryReport",
                "childList": [],
                "isCheck": true
              },
              {
                "businessMenuId": 1346,
                "menuCode": "m_005_005_002",
                "menuName": "金币场人数",
                "parentMenuCode": "m_005_005",
                "sysType": 1,
                "menuType": 1,
                "sort": 0,
                "disabled": false,
                "createTime": 1561433653000,
                "modifyTime": 1563269848000,
                "url": "/manager/report/goldtype/queryReport",
                "childList": [],
                "isCheck": true
              },
              {
                "businessMenuId": 1348,
                "menuCode": "m_005_005_003",
                "menuName": "金币场局数",
                "parentMenuCode": "m_005_005",
                "sysType": 1,
                "menuType": 1,
                "sort": 0,
                "disabled": false,
                "createTime": 1561433653000,
                "modifyTime": 1563269848000,
                "url": "/manager/report/goldtype/queryReport",
                "childList": [],
                "isCheck": true
              },
              {
                "businessMenuId": 1350,
                "menuCode": "m_005_005_004",
                "menuName": "金币场时长",
                "parentMenuCode": "m_005_005",
                "sysType": 1,
                "menuType": 1,
                "sort": 0,
                "disabled": false,
                "createTime": 1561433653000,
                "modifyTime": 1563269848000,
                "url": "/manager/report/goldtype/queryReport",
                "childList": [],
                "isCheck": true
              }
            ],
            "isCheck": true
          },
          {
            "businessMenuId": 1353,
            "menuCode": "m_005_006",
            "menuName": "活动数据",
            "parentMenuCode": "m_005",
            "sysType": 1,
            "menuType": 1,
            "sort": 0,
            "disabled": false,
            "createTime": 1561433653000,
            "modifyTime": 1564729433000,
            "url": "",
            "childList": [
              {
                "businessMenuId": 1354,
                "menuCode": "m_005_006_001",
                "menuName": "活动流水",
                "parentMenuCode": "m_005_006",
                "sysType": 1,
                "menuType": 1,
                "sort": 0,
                "disabled": false,
                "createTime": 1561433653000,
                "modifyTime": 1563867052000,
                "url": "/manager/activity/record/page",
                "childList": [],
                "isCheck": true
              },
              {
                "businessMenuId": 1355,
                "menuCode": "m_005_006_002",
                "menuName": "活动概况",
                "parentMenuCode": "m_005_006",
                "sysType": 1,
                "menuType": 1,
                "sort": 0,
                "disabled": false,
                "createTime": 1561433653000,
                "modifyTime": 1563867052000,
                "url": "/manager/activity/report/getSum,/manager/activity/report/queryList",
                "childList": [],
                "isCheck": true
              }
            ],
            "isCheck": true
          }
        ],
        "isCheck": true
      },
      {
        "businessMenuId": 1299,
        "menuCode": "m_006",
        "menuName": "客服",
        "parentMenuCode": "0",
        "sysType": 1,
        "menuType": 1,
        "sort": 0,
        "disabled": false,
        "createTime": 1560937801000,
        "modifyTime": 1560937940000,
        "url": null,
        "childList": [],
        "isCheck": true
      },
      {
        "businessMenuId": 1301,
        "menuCode": "m_008",
        "menuName": "游戏管理",
        "parentMenuCode": "0",
        "sysType": 1,
        "menuType": 1,
        "sort": 0,
        "disabled": false,
        "createTime": 1560937801000,
        "modifyTime": 1560937940000,
        "url": null,
        "childList": [],
        "isCheck": true
      },
      {
        "businessMenuId": 1337,
        "menuCode": "m_014",
        "menuName": "风控管理",
        "parentMenuCode": "0",
        "sysType": 1,
        "menuType": 1,
        "sort": 0,
        "disabled": false,
        "createTime": 1560937801000,
        "modifyTime": 1560937940000,
        "url": null,
        "childList": [
          {
            "businessMenuId": 1335,
            "menuCode": "m_014_001",
            "menuName": "风控配置",
            "parentMenuCode": "m_014",
            "sysType": 1,
            "menuType": 1,
            "sort": 0,
            "disabled": false,
            "createTime": 1560936641000,
            "modifyTime": 1563346583000,
            "url": "/manager/risk/config/queryPage,/manager/risk/config/insertOrUpdate,/manager/risk/config/getByBusinessRiskConfigId,/manager/risk/config/delete,/manager/risk/config/changeStatus",
            "childList": [],
            "isCheck": true
          },
          {
            "businessMenuId": 1336,
            "menuCode": "m_014_002",
            "menuName": "触发历史",
            "parentMenuCode": "m_014",
            "sysType": 1,
            "menuType": 1,
            "sort": 0,
            "disabled": false,
            "createTime": 1560936641000,
            "modifyTime": 1563264288000,
            "url": "/manager/risk/history/queryPage",
            "childList": [],
            "isCheck": true
          }
        ],
        "isCheck": true
      }
    ],
    "ip": "119.39.90.56"
  }
}